### PR TITLE
interpret_csi_SGR: optimize reset and never recurse

### PR DESCRIPTION
**Pull request by lwi**
I extended my change to get rid of the recursion. The semantics remain exactly the same.

### CODE REVIEW

**Comment by TragicWarrior** [comment]
@lwi , can you rebase this pull request.  it has conflicts with master right now.

**Comment by lwi** [comment]
done

**Comment by lwi** [comment]
rebased

**Comment by TragicWarrior** [comment]
@lwi , looks good.  before I implemented the jump table this would not have been possible (the fall through approach).  like it!

**Pull request merged**
